services:
  app:
    image: ghcr.io/cncnet/cncnet-ladder-app:${APP_TAG}
    restart: unless-stopped
    container_name: cncnet_ladder_app
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    env_file: ".app.env"
    environment:
      XDG_CONFIG_HOME: /app/.config
      XDG_DATA_HOME: /app/.data
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./storage:/app/storage
    ports:
      - '${APP_PORT:-3000}:8000'
    depends_on:
      - redis
    networks:
      - cncnet

  queue-findmatch:
    image: ghcr.io/cncnet/cncnet-ladder-queue:${APP_TAG}
    restart: unless-stopped
    container_name: cncnet_ladder_queue_findmatch
    depends_on:
      - app
    env_file: ".app.env"
    environment:
      QUEUE_NAME: 'findmatch'
    networks:
      - cncnet

  queue-saveladderresult:
    image: ghcr.io/cncnet/cncnet-ladder-queue:${APP_TAG}
    restart: unless-stopped
    container_name: cncnet_ladder_queue_saveladderresult
    depends_on:
      - app
    env_file: ".app.env"
    environment:
      QUEUE_NAME: 'saveladderresult'
    networks:
      - cncnet

  scheduler:
    image: ghcr.io/cncnet/cncnet-ladder-scheduler:${APP_TAG}
    restart: always
    container_name: cncnet_ladder_scheduler
    depends_on:
      - app
    env_file: ".app.env"
    networks:
      - cncnet

  redis:
    image: 'redis:alpine'
    container_name: cncnet_ladder_redis
    volumes:
      - redis:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    networks:
      - cncnet

  mysql:
    image: mariadb:latest
    container_name: cncnet_ladder_mysql
    restart: unless-stopped
    command: --max_connections=1000 --max_allowed_packet=128M --log_warnings=3 --wait_timeout=31536000 --slow-query-log --interactive_timeout=31536000
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - cncnet-ladder-db:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # Import latest db tables on init
    networks:
      - cncnet

  db-backup:
    container_name: cncnet_ladder_backup
    env_file:
      - '.backup.env'
    image: tiredofit/db-backup
    volumes:
      - ./backups:/backup
    restart: always
    links:
      - mysql
    networks:
      - cncnet

volumes:
  caddy_data:
  caddy_config:
  redis:
  cncnet-ladder-db:
    driver: local

networks:
  cncnet:
    driver: bridge