version: "3.3"

services:
    app:
        build:
            args:
                user: ${HOST_USER}
                uid: ${HOST_UID}
            context: .
            dockerfile: ./docker/Dockerfile
        env_file: ./src/.env
        volumes:
            - ./src:/home/${HOST_USER}/site
        networks:
            - cncnet

    nginx:
        image: nginx:stable-alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/home/${HOST_USER}/site
            - ./docker/nginx/templates:/etc/nginx/templates/
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
            HOST_USER: ${HOST_USER}
        networks:
            - cncnet

    mysql:
        image: mysql
        restart: always
        env_file: ./src/.env
        volumes:
            - cncnet-ladder-db:/var/lib/mysql
            - ./docker/mysql/tables.sql:/docker-entrypoint-initdb.d/tables.sql # Import latest db tables on init 
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
        networks:
            - cncnet

networks:
    cncnet:
        driver: bridge

volumes:
    cncnet-ladder-db:
        driver: local

    cncnet-ladder-db-import:
        driver: local