services:
  app:
    image: ghcr.io/cncnet/cncnet-ladder-app:${APP_TAG}
    restart: unless-stopped
    container_name: cncnet_ladder_app${ENV_SUFFIX}
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    env_file: ".app.env"
    environment:
      XDG_CONFIG_HOME: /app/.config
      XDG_DATA_HOME: /app/.data
    volumes:
      - ./caddy/data:/app/.data
      - ./caddy/config:/app/.config
      - ./storage:/app/storage
    ports:
      - '${APP_PORT:-3000}:8000'
    depends_on:
      - redis
      - mysql
    networks:
      - cncnet

  queue-findmatch:
    image: ghcr.io/cncnet/cncnet-ladder-queue:${APP_TAG}
    restart: unless-stopped
    container_name: cncnet_ladder_queue_findmatch${ENV_SUFFIX}
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    depends_on:
      - app
    env_file: ".app.env"
    environment:
      QUEUE_NAME: 'findmatch'
    volumes:
      - ./storage:/app/storage
    networks:
      - cncnet

  queue-saveladderresult:
    image: ghcr.io/cncnet/cncnet-ladder-queue:${APP_TAG}
    restart: unless-stopped
    container_name: cncnet_ladder_queue_saveladderresult${ENV_SUFFIX}
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    depends_on:
      - app
    env_file: ".app.env"
    environment:
      QUEUE_NAME: 'saveladderresult'
    volumes:
      - ./storage:/app/storage
    networks:
      - cncnet

  scheduler:
    image: ghcr.io/cncnet/cncnet-ladder-scheduler:${APP_TAG}
    restart: unless-stopped
    container_name: cncnet_ladder_scheduler${ENV_SUFFIX}
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    depends_on:
      - app
    env_file: ".app.env"
    volumes:
      - ./storage:/app/storage
    networks:
      - cncnet

  redis:
    image: 'redis:alpine'
    container_name: cncnet_ladder_redis${ENV_SUFFIX}
    volumes:
      - redis:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    networks:
      - cncnet

  mysql:
    image: mariadb:latest
    container_name: cncnet_ladder_mysql${ENV_SUFFIX}
    restart: unless-stopped
    command: --max_connections=500 --max_allowed_packet=128M --log_warnings=3 --wait_timeout=600 --slow-query-log --interactive_timeout=600 --long_query_time=0.5
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - cncnet-ladder-db:/var/lib/mysql
    networks:
      - cncnet

  db-backup:
    container_name: cncnet_ladder_backup${ENV_SUFFIX}
    env_file:
      - '.backup.env'
    image: tiredofit/db-backup
    volumes:
      - ./backups:/backup
    restart: always
    links:
      - mysql
    networks:
      - cncnet

  elogen:
    image: ghcr.io/cncnet/cncnet-ladder-elo-computation-cron:latest
    restart: unless-stopped
    container_name: cncnet_ladder_elogen${ENV_SUFFIX}
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
    volumes:
      - ./docker/elogen/crontab:/mnt/crontab:ro
      - ./storage/app/rating:/data
    depends_on:
      - mysql
    networks:
      - cncnet

volumes:
  caddy_data:
  caddy_config:
  redis:
  cncnet-ladder-db:
    driver: local

networks:
  cncnet:
    driver: bridge
